version: '3'

services:
  nginx:
    container_name: tournaments_nginx
    image: nginx
    volumes:
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './src/:/var/www/html'
    ports:
      - '80:80'
    depends_on:
      - php
      - database

  php:
    container_name: tournaments_php
    build: .docker/php
    user: '${UID}:${GID}'
    volumes:
      - './.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './src/:/var/www/html'

  composer:
    container_name: tournaments_composer
    image: composer:latest
    user: '${UID}:${GID}'
    volumes:
      - './src/:/app'
    command: update

  database:
    container_name: tournaments_database
    image: postgres:13.1
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-database:/var/lib/postgresql/data'

volumes:
  postgres-database:
    driver: local